import type { Metadata } from "next";
import "./globals.css";
import "../components/navbar"
import { SessionProvider } from "@/context/context";
import LayoutContent from "@/components/LayoutContent";

export const metadata: Metadata = {
  title: "Ephraim Akai-Nettey - Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <LayoutContent>
            {children}
          </LayoutContent>
        </body>
      </html>
    </SessionProvider>    
  );
}
