import type { Metadata } from "next";
import "./globals.css";
import "../components/navbar"
import Navbar from "@/components/navbar";
import { SessionProvider } from "@/context/context";


export const metadata: Metadata = {
  title: "Ephraim Akai-Nettey - Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
        <html lang="en">
          <body
            className={`antialiased`}
          >
            <Navbar/>
            <div className="lg:w-[60%] w-[75%] md:w-[70%] mx-auto">
              {children}
            </div>     
          </body>
        </html>
    </SessionProvider>    
  );
}
